name: Snapshot UVOD (Puppeteer)

on:
  workflow_dispatch:
    inputs:
      start_url:
        description: "Start URL (must be under hjftm.github.io/uvod/)"
        required: false
        default: "https://hjftm.github.io/uvod/"
      max_pages:
        description: "Safety limit"
        required: false
        default: "800"

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          npm init -y
          npm pkg set type="module"
          npm i puppeteer@23

      - name: Add snapshot script
        run: |
          mkdir -p scripts
          # Ako je skripta već u repozitoriju, ovaj korak preskoči ili zamijeni 'cat <<' slijedećim
          # OVDJE NE STAVLJAJ SKRIPTU – već si je dodao ručno – ovaj korak služi samo kao primjer.
          echo "OK"

      - name: Run snapshot
        env:
          START_URL: ${{ github.event.inputs.start_url || 'https://hjftm.github.io/uvod/' }}
          OUT_DIR: snapshot-uvod
          MAX_PAGES: ${{ github.event.inputs.max_pages || '800' }}
          CONCURRENCY: "4"
          WAIT_MS: "800"
          NAV_TIMEOUT: "45000"
        run: |
          node main/hello-framework/scripts/snapshot-uvod.js

      - name: Pack ZIP
        run: |
          ts=$(date +'%Y%m%d-%H%M')
          zip -r "uvod-snapshot-$ts.zip" snapshot-uvod
          echo "ZIP_NAME=uvod-snapshot-$ts.zip" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: ${{ env.ZIP_NAME }}

      - name: Commit ZIP into web/
        run: |
          mkdir -p web
          mv "${ZIP_NAME}" web/
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add web/"${ZIP_NAME}"
          git commit -m "Add UVOD snapshot ${ZIP_NAME}" || echo "No changes"
          git push || true
